### ISSUE TITLE
Get timezone from user and apply conversion logic for user jobs

### ISSUE THREAD

**Issue by iMel408** [iMel408/texts_to_self#3]
- [x] create user input for desired time and timezone
- [x] update user table and jobs tables
- [x] convert user selected time to utc using their selected tz
- [x] convert utc time to user tz in the setup/update/user page ui.

**Comment by iMel408** [comment]
@arjunmehta94 & @dbuscaglia - Hey guys, any advice on whether it makes more sense to just store the users tz choice and do the conversion every time I query to identify jobs that need to be run (at current hour) instead of storing both the users choice and converted [hour] value?

**Comment by arjunmehta94** [comment]
It's probably easier, and typically the standard, that the database values
be timezone agnostic. They would typically default to UTC time. It's
probably easier to just convert all user inputs to one standard and store
it as that. That way you don't need to worry about which jobs need to run
based on timezone.

**Comment by iMel408** [comment]
Timezone conversions are no joke... Doing something super hacky for now (mvp due).  Just found out about Arrow (pypi.org/project/arrow/) and plan on refactoring to use it later.
@arjunmehta94  -  Could you take a look at my time conversion logic when you have a minute to spare? Thnx!
